// ── Classic Dungeon Progression ─────────────────────────────────────
// The default 12-floor dungeon crawl: rats in the cellar, dragon at the end.

import type { ProgressionRecipe } from './types';

export const CLASSIC: ProgressionRecipe = {
  name: 'Classic',
  description: '12-floor dungeon crawl with 4 zones, escalating from rats to dragons.',

  zones: [
    {
      floors: [1, 3],
      zoneName: 'Upper Cellars',
      pool: {
        low:     ['rat', 'bat', 'imp', 'goblin', 'blob', 'spider'],
        mid:     ['skeleton'],
        high:    [],
        weights: [8, 2, 0],
      },
      densityMult: 1.0,
      hpMult: 1.0,
      damageMult: 1.0,
      dungeonSize: 24,
      roomSpacing: 4,
      heightChance: 0.1,
      doorChance: 0.85,
      loopChance: 0.0,
    },
    {
      floors: [4, 6],
      zoneName: 'Haunted Halls',
      pool: {
        low:     ['rat', 'goblin', 'spider', 'imp'],
        mid:     ['skeleton', 'zombie', 'ghost', 'hobgoblin', 'wolf'],
        high:    ['mimic'],
        weights: [4, 5, 1],
      },
      densityMult: 1.0,
      hpMult: 1.2,
      damageMult: 1.1,
      dungeonSize: 32,
      roomSpacing: 3,
      heightChance: 0.3,
      doorChance: 0.8,
      loopChance: 0.15,
    },
    {
      floors: [7, 9],
      zoneName: 'Deep Warren',
      pool: {
        low:     ['spider', 'imp'],
        mid:     ['werewolf', 'bugbear', 'gargoyle', 'hobgoblin', 'wolf'],
        high:    ['vampire', 'mimic'],
        weights: [2, 5, 3],
      },
      densityMult: 1.0,
      hpMult: 1.5,
      damageMult: 1.3,
      dungeonSize: 40,
      roomSpacing: 3,
      heightChance: 0.5,
      doorChance: 0.7,
      loopChance: 0.4,
    },
    {
      floors: [10, 12],
      zoneName: 'Abyssal Depths',
      pool: {
        low:     [],
        mid:     ['gargoyle', 'werewolf', 'bugbear'],
        high:    ['devil', 'beholder', 'minotaur', 'golem', 'hydra', 'dragon'],
        weights: [0, 3, 7],
      },
      densityMult: 1.0,
      hpMult: 2.0,
      damageMult: 1.5,
      dungeonSize: 48,
      roomSpacing: 2,
      heightChance: 0.65,
      doorChance: 0.8,
      loopChance: 0.55,
    },
  ],

  roomAffinity: {
    crypt:       ['skeleton', 'zombie', 'ghost'],
    tomb_vault:  ['skeleton', 'zombie', 'ghost', 'vampire'],
    library:     ['ghost', 'imp', 'spider'],
    study:       ['ghost', 'imp', 'spider'],
    chapel:      ['ghost', 'gargoyle'],
    shrine:      ['ghost', 'gargoyle'],
    barracks:    ['hobgoblin', 'goblin', 'skeleton'],
    guard:       ['hobgoblin', 'goblin', 'skeleton'],
    jail:        ['skeleton', 'zombie', 'rat'],
    cell:        ['skeleton', 'zombie', 'rat'],
    kitchen:     ['rat', 'goblin', 'blob'],
    pantry:      ['rat', 'goblin', 'blob'],
    cellar:      ['rat', 'spider', 'blob'],
    storage:     ['rat', 'spider', 'blob'],
    treasure:    ['mimic', 'goblin'],
    trophy:      ['mimic', 'goblin'],
    trap:        ['spider', 'mimic', 'imp'],
    bar:         ['goblin', 'hobgoblin', 'rat'],
    dining:      ['goblin', 'hobgoblin', 'rat'],
    alchemy:     ['imp', 'ghost', 'spider'],
  },
  roomAffinityBoost: 3,

  themedFloors: [
    {
      floor: 5,
      title: 'The Bone Pit',
      subtitle: 'The dead do not rest easy here.',
      bossArchetype: 'skeleton',
      bossCount: 3,
      exclusivePool: ['skeleton', 'zombie', 'ghost'],
    },
    {
      floor: 8,
      title: "The Necromancer's Domain",
      subtitle: 'Dark magic permeates the air.',
      bossArchetype: 'vampire',
      bossCount: 2,
      exclusivePool: ['ghost', 'skeleton', 'zombie', 'vampire'],
    },
    {
      floor: 12,
      title: "Dragon's Lair",
      subtitle: 'The ancient one awaits.',
      bossArchetype: 'dragon',
      bossCount: 1,
    },
  ],

  overshootScaling: {
    hpPerFloor: 0.25,
    damagePerFloor: 0.15,
    dungeonSizePerFloor: 2,
  },
};
